use_frameworks!

platform :ios, '8.0'

target 'VVDataItem_Example' do
  pod 'VVDataItem' , :path => '../'

  target 'VVDataItem_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
